### ISSUE TITLE
ParseSDK 1.7 compatibality

### ISSUE THREAD

**Issue by ihsanberahim** [avivais/phonegap-parse-plugin#20]
i want receive parse intent

`
        <receiver android:exported="false" android:name="com.my.app.Receiver">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.OPEN" />
                <action android:name="com.parse.push.intent.DELETE" />
            </intent-filter>
        </receiver>
`

Receiver.java use com.parse.ParsePushBroadcastReceiver.

I found the import in Parse SDK 1.7.
After i update parse sdk in the plugin.
The app force close upon launching.

Anybody succeed develop cordova (4.X) app with Parse SDK 1.7?

**Comment by dcartertwo** [comment]
When i try an use this updated fork i get the following error
```
BUILD FAILED
/Users/danielcarter/Downloads/android-sdk-macosx/tools/ant/build.xml:720: The following error occurred while executing this line:
/Users/danielcarter/Downloads/android-sdk-macosx/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

Total time: 1 second

/Users/danielcarter/Documents/code/teleport/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f,/Users/danielcarter/Documents/code/teleport/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
Error: /Users/danielcarter/Documents/code/teleport/platforms/android/cordova/run: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```
Adding here because I can't add an issue to the forked repo

**Comment by ihsanberahim** [comment]
thx for remind me that.
https://github.com/ihsanberahim/phonegap-parse-plugin (already open the issue tracker)

try clean project

cordova platform add android
cordova plugin add plugin <above>
cordova build android

no need extra modification except the parse javaclass push receiver one.

**Comment by dcartertwo** [comment]
Yes, I tried that.  I also noticed that the build fails, and it looks like it is missing a dependency.  Any idea how to get this added? I see the jar in the folder, but I am guessing it is not being put in.  I also tried to add it to the plugin.xml.

```
-compile:
    [javac] Compiling 5 source files to /Users/danielcarter/Documents/code/teleport/platforms/android/ant-build/classes
    [javac] /Users/danielcarter/Documents/code/teleport/platforms/android/src/org/apache/cordova/core/ParsePlugin.java:66: cannot access bolts.Task
    [javac] class file for bolts.Task not found
    [javac]                     ParseInstallation.getCurrentInstallation().saveInBackground();
    [javac]                                                                                ^
    [javac] 1 error
```

**Comment by ihsanberahim** [comment]
Sorry. I don't know why it happen to you. I don't need the bolt in my project.

But,

Try manually fix by copy bolt-android from
```
cp $codova_project/plugins/org.apache.cordova.core.parseplugin/src/android/parse/bolts-android-1.1.3.jar $codova_project/platforms/android/libs/bolts-android-1.1.3.jar
```
before you compile your project, try clean project build by doing:

```
cd $codova_project/platforms/android/
ant clean
cd ../../
cordova build android
```

**Comment by dcartertwo** [comment]
Thanks.  I have tried this as well.  I actually don't need bolt for my project either (as far as I know) this error appears when I try and build my project using your fork.  The only plugins I have are yours and the phonegap-pushplugin.
