### ISSUE TITLE
Parse/Parse.h file not found - Xcode 6

### ISSUE THREAD

**Issue by bluety** [avivais/phonegap-parse-plugin#43]
When I open my project with Xcode I have an error:
> Parse/Parse.h file not found

**Comment by castillobg** [comment]
I had the same problem yesterday. The class was under a 'Version' folder. Just that folder's content to the folder it's supposed to be in and voilà.

**Comment by bluety** [comment]
But where it is supposed to be in ?

Actualy it looks like:
MyApp/platforms/ios/appName/Plugins/com.parse.cordova.core.pushplugin/Parse.framework/Versions/1.2.16

**Comment by castillobg** [comment]
Then copy de contents of 1.2.16 into Parse.framework :)

**Comment by bluety** [comment]
It works ! thank you

**Comment by grrrian** [comment]
I am still having this issue every time I do:
$ cordova plugin add https://github.com/avivais/phonegap-parse-plugin
$ ionic platform rm ios
$ ionic platform add ios

In order to fix it, I need to open the project with XCode6, remove and add Parse.framework. It doesn't make much sense since am removing and adding the same file. There is no Version/ subfolder.

**Comment by kukusumaa** [comment]
Hi @bluety, i try to copy the contents of 1.2.16 into Parse.framework too but i get an error : 

Undefined symbols for architecture i386:
"FBTokenInformationExpirationDateKey", referenced from:
-[PFFacebookTokenCachingStrategy cacheTokenInformation:] in Parse(PFFacebookTokenCachingStrategy.o)
-[PFFacebookTokenCachingStrategy expirationDate] in Parse(PFFacebookTokenCachingStrategy.o)
-[PFFacebookTokenCachingStrategy setExpirationDate:] in Parse(PFFacebookTokenCachingStrategy.o)
"_FBTokenInformationTokenKey", referenced from:
-[PFFacebookTokenCachingStrategy accessToken] in Parse(PFFacebookTokenCachingStrategy.o)
-[PFFacebookTokenCachingStrategy setAccessToken:] in Parse(PFFacebookTokenCachingStrategy.o)
"_FBTokenInformationUserFBIDKey", referenced from:
-[PFFacebookTokenCachingStrategy facebookId] in Parse(PFFacebookTokenCachingStrategy.o)
-[PFFacebookTokenCachingStrategy setFacebookId:] in Parse(PFFacebookTokenCachingStrategy.o)
"_OBJC_CLASS$FBAppCall", referenced from:
objc-class-ref in Parse(PFFacebookAuthenticationProvider.o)
"_OBJC_CLASS$FBRequest", referenced from:
objc-class-ref in Parse(PFFacebookAuthenticationProvider.o)
"_OBJC_CLASS$FBSession", referenced from:
objc-class-ref in Parse(PFFacebookAuthenticationProvider.o)
"_OBJC_CLASS$FBSessionTokenCachingStrategy", referenced from:
_OBJC_CLASS$PFFacebookTokenCachingStrategy in Parse(PFFacebookTokenCachingStrategy.o)
"_OBJC_METACLASS$FBSessionTokenCachingStrategy", referenced from:
_OBJC_METACLASS$_PFFacebookTokenCachingStrategy in Parse(PFFacebookTokenCachingStrategy.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could you help me to solve it?
Thank you

**Comment by bluety** [comment]
Hi, you must install facebook SDK
https://developers.facebook.com/docs/ios
