### ISSUE TITLE
Only receive notifications if the app is open

### ISSUE THREAD

**Issue by Tiagojdferreira** [avivais/phonegap-parse-plugin#54]
I am developing an app using the ionic framework. I have managed to register the device and receive push notifications, but only has long as the app is running.
My code currently consists of just registering the device using the parsePlugin.initialize.

Found this, will look into it:
https://www.parse.com/questions/push-notification-in-android-while-app-closed

**Comment by budda** [comment]
Did you take note of the Android "Quirks" section of the Readme and add in the App.java class?
